### ISSUE TITLE
Birthday success

### ISSUE THREAD

**Issue by thyristor59** [reuterbal/photobooth#71]
**Describe your photobooth**
 I recently used this software for a test before friend marriage. Everything passed well!
My material(equipment) was only a digital reflex, a screen, a mouse connected(bound) in my raspberry pi.

**Hardware (please complete the following information):**
 - Device Raspberry Pi 3B+
 - Camera Nikon D5000
 - GPIO: No
- Printer Canon CP1300
 
 **Additional equipment**
  - No

**Software (please complete the following information):**
 - OS raspbian
 - Python version 3.6

**Problems:**
 Rasperry stop 3x 
Complete stop(ruling) without reason of the software but has cause of the heat. The raspberry was locked and just behind the screen. I think that it is the reason

**Pictures:**

![img_20181118_113627](https://user-images.githubusercontent.com/42303881/49091371-ff123b80-f25f-11e8-8247-47c692ea12cb.jpg)

50 was print

**Comment by reuterbal** [comment]
Thanks for taking the time to write your feedback! Glad to hear that it worked mostly fine. 

Regarding the heat issue: are you using a heat sink on your Raspberry Pi? I found that this significantly improves heat issues and, in the same way, ensures better performance because the clock frequency isn't reduced as often.

**Comment by wikijm** [comment]
Hi @thyristor59,

I'll be able to see you 'Success story' on the [wiki](https://github.com/reuterbal/photobooth/wiki/Success-stories) now 😃

Thanks for your feedback 👍

**Comment by wikijm** [comment]
As this is included in the Wiki now, I'll close this.
