### ISSUE TITLE
Succès  but

### ISSUE THREAD

**Issue by thyristor59** [reuterbal/photobooth#77]
Hello!!!
Here is another example of success!
![img_20190103_165701](https://user-images.githubusercontent.com/42303881/50648213-e261d580-0f7a-11e9-9237-fbce7e9092b1.jpg)

But:

however, with the advice of my friends to optimize the wedding day:

-how do I put the "print" and "start again" functions at the top of the screen
![img_20190103_171243](https://user-images.githubusercontent.com/42303881/50648205-dc6bf480-0f7a-11e9-8ffc-216fda927f53.jpg)

- flash / lighting problem (under research)
- huge slowdown of the printer.

all his questions are according to my furniture creation.
![img_20181218_164334_hdr](https://user-images.githubusercontent.com/42303881/50648238-f86f9600-0f7a-11e9-9533-366ecb968a94.jpg)

if you have ideas or solutions I would be delighted! For ligth and flash
thank you in advance

**Comment by reuterbal** [comment]
Thank you for sharing your story!

To modify the layout you can try to achieve this by changing the stylesheet [`photobooth/gui/Qt5Gui/stylesheets/pastel-1024x600.qss`](https://github.com/reuterbal/photobooth/blob/master/photobooth/gui/Qt5Gui/stylesheets/pastel-1024x600.qss). I'm not sure how much you can change the positioning of items in there using the Qt-CSS-subset.
Otherwise you will have to modify `PostprocessMessage` in [`photobooth/gui/Qt5Gui/Frames.py`](https://github.com/reuterbal/photobooth/blob/master/photobooth/gui/Qt5Gui/Frames.py)

**Comment by reuterbal** [comment]
When I find time I will include your success story in the Wiki. Maybe you could add some details about the employed hardware (camera, Raspberry, screen, Printer, etc.)?

**Comment by wikijm** [comment]
Hi @reuterbal 

🎉My best wishes for 2019  🎉

It's seems that @thyristor59 already did the job with #71, which is then already in the Wiki 😜

**Comment by reuterbal** [comment]
Well observed - I included the link to this one.

**Comment by MarioJanssen27** [comment]
Is that a mirror as a display?

**Comment by thyristor59** [comment]
Yes, it is an unstained window for the mirror effect when the software does not take pictures.
it looks more like a mirror connect than a classic photobooth
